# Generated by Django 5.2.7 on 2025-11-10 22:10

import apps.users.models
from django.core.exceptions import ValidationError
from django.db import migrations, models


def validate_image_size(image):
    """Validate uploaded image file size (max 5MB)."""
    max_size_mb = 5
    max_size_bytes = max_size_mb * 1024 * 1024
    if image.size > max_size_bytes:
        msg = f"Image file size cannot exceed {max_size_mb}MB"
        raise ValidationError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[validate_image_size],
                verbose_name="avatar",
            ),
        ),
    ]
