# Generated by Django 5.2.7 on 2026-06-13 22:29

import apps.users.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.users.models.users.validate_image_size], verbose_name='avatar'),
        ),
    ]
