# Generated by Django 5.2.7 on 2026-03-16 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gigs', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='gigs.gig', verbose_name='gig')),
                ('participant_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p1', to='professionals.professionalprofile', verbose_name='participant 1')),
                ('participant_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p2', to='professionals.professionalprofile', verbose_name='participant 2')),
            ],
            options={
                'ordering': ['-modified'],
                'unique_together': {('participant_1', 'participant_2', 'gig')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('body', models.TextField(verbose_name='body')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='professionals.professionalprofile', verbose_name='sender')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
