// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type Conversation = {
    readonly uuid: string;
    participant_1: ProfessionalProfile;
    participant_2: ProfessionalProfile;
    readonly gig: string;
    readonly last_message: {
        [key: string]: unknown;
    } | null;
    readonly unread_count: number;
    readonly modified: string;
};

export type ConversationCreate = {
    participant_uuid: string;
    gig_uuid?: string | null;
};

export type ConversationCreateRequest = {
    participant_uuid: string;
    gig_uuid?: string | null;
};

/**
 * Custom JWT serializer that uses email and checks email verification.
 */
export type EmailTokenObtainPairRequest = {
    email: string;
    password: string;
};

/**
 * Read serializer for gig list/detail.
 */
export type Gig = {
    readonly uuid: string;
    title: string;
    description?: string;
    location_address: string;
    /**
     * Location latitude
     */
    location_lat?: string | null;
    /**
     * Location longitude
     */
    location_lng?: string | null;
    scheduled_date: string;
    scheduled_time: string;
    /**
     * Budget range minimum
     */
    budget_range_min?: string | null;
    /**
     * Budget range maximum
     */
    budget_range_max?: string | null;
    readonly agreed_price: string | null;
    status: Status92cEnum;
    gig_type?: GigTypeEnum;
    posted_by: ProfessionalProfile;
    assigned_to: ProfessionalProfile;
    readonly created: string;
    readonly modified: string;
};

/**
 * Serializer for creating gigs.
 */
export type GigCreate = {
    title: string;
    description?: string;
    location_address: string;
    /**
     * Location latitude
     */
    location_lat?: string | null;
    /**
     * Location longitude
     */
    location_lng?: string | null;
    scheduled_date: string;
    scheduled_time: string;
    /**
     * Budget range minimum
     */
    budget_range_min?: string | null;
    /**
     * Budget range maximum
     */
    budget_range_max?: string | null;
    gig_type?: GigTypeEnum;
};

/**
 * Serializer for creating gigs.
 */
export type GigCreateRequest = {
    title: string;
    description?: string;
    location_address: string;
    /**
     * Location latitude
     */
    location_lat?: string | null;
    /**
     * Location longitude
     */
    location_lng?: string | null;
    scheduled_date: string;
    scheduled_time: string;
    /**
     * Budget range minimum
     */
    budget_range_min?: string | null;
    /**
     * Budget range maximum
     */
    budget_range_max?: string | null;
    gig_type?: GigTypeEnum;
};

/**
 * Read serializer for gig invitations.
 */
export type GigInvitation = {
    readonly uuid: string;
    invited_agent: ProfessionalProfile;
    proposed_rate?: string | null;
    message?: string;
    status?: GigInvitationStatusEnum;
    readonly created: string;
};

/**
 * Serializer for creating gig invitations.
 */
export type GigInvitationCreate = {
    invited_agent_uuid: string;
    message?: string;
};

/**
 * Serializer for creating gig invitations.
 */
export type GigInvitationCreateRequest = {
    invited_agent_uuid: string;
    message?: string;
};

/**
 * Read serializer for gig invitations.
 */
export type GigInvitationRequest = {
    proposed_rate?: string | null;
    message?: string;
    status?: GigInvitationStatusEnum;
};

/**
 * * `pending` - Pending
 * * `accepted` - Accepted
 * * `declined` - Declined
 * * `withdrawn` - Withdrawn
 */
export type GigInvitationStatusEnum = 'pending' | 'accepted' | 'declined' | 'withdrawn';

/**
 * Read serializer for gig list/detail.
 */
export type GigRequest = {
    title: string;
    description?: string;
    location_address: string;
    /**
     * Location latitude
     */
    location_lat?: string | null;
    /**
     * Location longitude
     */
    location_lng?: string | null;
    scheduled_date: string;
    scheduled_time: string;
    /**
     * Budget range minimum
     */
    budget_range_min?: string | null;
    /**
     * Budget range maximum
     */
    budget_range_max?: string | null;
    gig_type?: GigTypeEnum;
};

/**
 * Validates gig status transitions.
 */
export type GigStatusTransitionRequest = {
    status: Status92cEnum;
};

/**
 * * `showing` - Showing
 * * `open_house` - Open House
 * * `inspection_accompaniment` - Inspection Accompaniment
 * * `other` - Other
 */
export type GigTypeEnum = 'showing' | 'open_house' | 'inspection_accompaniment' | 'other';

/**
 * * `pending_verification` - Pending Verification
 * * `verified` - Verified
 * * `rejected` - Rejected
 * * `expired` - Expired
 */
export type LicenseStatusEnum = 'pending_verification' | 'verified' | 'rejected' | 'expired';

export type Message = {
    readonly uuid: string;
    sender: ProfessionalProfile;
    body: string;
    readonly read_at: string | null;
    readonly created: string;
};

export type MessageCreate = {
    body: string;
};

export type MessageCreateRequest = {
    body: string;
};

export type Metro = {
    readonly uuid: string;
    name: string;
    state: string;
};

export type MetroRequest = {
    name: string;
    state: string;
};

/**
 * Extended serializer that includes private fields for the profile owner.
 */
export type MyProfessionalProfile = {
    readonly uuid: string;
    readonly user_email: string;
    readonly user_first_name: string;
    readonly user_last_name: string;
    readonly user_avatar: string;
    license_status: LicenseStatusEnum;
    readonly service_areas: Array<ServiceArea>;
    readonly specializations: Array<SpecializationsEnum>;
    readonly bio: string;
    readonly average_rating: string | null;
    readonly average_response_time: string | null;
    readonly is_available: boolean;
    readonly is_verified: boolean;
    readonly license_number: string;
    readonly license_expiry: string | null;
    readonly verified_at: string | null;
    readonly rejection_reason: string;
};

/**
 * Serializer for OTP email verification.
 */
export type OtpVerification = {
    email: string;
    code: string;
};

/**
 * Serializer for OTP email verification.
 */
export type OtpVerificationRequest = {
    email: string;
    code: string;
};

export type PaginatedConversationList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Conversation>;
};

export type PaginatedGigInvitationList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<GigInvitation>;
};

export type PaginatedGigList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Gig>;
};

export type PaginatedMessageList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Message>;
};

export type PaginatedMetroList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Metro>;
};

export type PaginatedProfessionalProfileList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ProfessionalProfile>;
};

export type PaginatedReviewList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Review>;
};

export type PaginatedServiceAreaList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ServiceArea>;
};

export type PaginatedUserList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<User>;
};

/**
 * Serializer for changing password (authenticated users).
 */
export type PasswordChangeRequest = {
    old_password: string;
    new_password: string;
};

/**
 * Serializer for password reset confirmation.
 */
export type PasswordResetConfirm = {
    token: string;
};

/**
 * Serializer for password reset confirmation.
 */
export type PasswordResetConfirmRequest = {
    token: string;
};

/**
 * Serializer for OTP-based password reset confirmation.
 */
export type PasswordResetOtpConfirm = {
    email: string;
    code: string;
};

/**
 * Serializer for OTP-based password reset confirmation.
 */
export type PasswordResetOtpConfirmRequest = {
    email: string;
    code: string;
};

/**
 * Serializer for OTP-based password reset request.
 */
export type PasswordResetOtpRequest = {
    email: string;
};

/**
 * Serializer for OTP-based password reset request.
 */
export type PasswordResetOtpRequestRequest = {
    email: string;
};

/**
 * Serializer for password reset request.
 */
export type PasswordResetRequest = {
    email: string;
};

/**
 * Serializer for password reset request.
 */
export type PasswordResetRequestRequest = {
    email: string;
};

/**
 * Read serializer for gig invitations.
 */
export type PatchedGigInvitationRequest = {
    proposed_rate?: string | null;
    message?: string;
    status?: GigInvitationStatusEnum;
};

/**
 * Read serializer for gig list/detail.
 */
export type PatchedGigRequest = {
    title?: string;
    description?: string;
    location_address?: string;
    /**
     * Location latitude
     */
    location_lat?: string | null;
    /**
     * Location longitude
     */
    location_lng?: string | null;
    scheduled_date?: string;
    scheduled_time?: string;
    /**
     * Budget range minimum
     */
    budget_range_min?: string | null;
    /**
     * Budget range maximum
     */
    budget_range_max?: string | null;
    gig_type?: GigTypeEnum;
};

/**
 * Serializer for creating/updating own professional profile.
 */
export type PatchedProfessionalProfileCreateRequest = {
    license_number?: string;
    bio?: string;
    specializations?: Array<SpecializationsEnum>;
    is_available?: boolean;
};

/**
 * Serializer for user model.
 */
export type PatchedUserRequest = {
    first_name?: string;
    last_name?: string;
    /**
     * Email address
     */
    email?: string;
    avatar?: Blob | File | null;
};

export type PaymentDetailResponse = {
    id: string;
    gig_uuid: string;
    stripe_payment_intent_id: string;
    amount: string;
    platform_fee: string;
    status: string;
};

/**
 * Read-only serializer for viewing professional profiles (public).
 */
export type ProfessionalProfile = {
    readonly uuid: string;
    readonly user_email: string;
    readonly user_first_name: string;
    readonly user_last_name: string;
    readonly user_avatar: string;
    license_status: LicenseStatusEnum;
    readonly service_areas: Array<ServiceArea>;
    readonly specializations: Array<SpecializationsEnum>;
    readonly bio: string;
    readonly average_rating: string | null;
    readonly average_response_time: string | null;
    readonly is_available: boolean;
    readonly is_verified: boolean;
};

/**
 * Serializer for creating/updating own professional profile.
 */
export type ProfessionalProfileCreateRequest = {
    license_number: string;
    bio?: string;
    specializations?: Array<SpecializationsEnum>;
    is_available?: boolean;
};

/**
 * Serializer for resending OTP to unverified email.
 */
export type ResendOtp = {
    email: string;
};

/**
 * Serializer for resending OTP to unverified email.
 */
export type ResendOtpRequest = {
    email: string;
};

export type Review = {
    readonly uuid: string;
    reviewer: ProfessionalProfile;
    readonly rating: number;
    readonly comment: string;
    readonly is_from_poster: boolean;
    readonly created: string;
};

export type ReviewCreate = {
    gig_uuid: string;
    rating: number;
    comment?: string;
};

export type ReviewCreateRequest = {
    gig_uuid: string;
    rating: number;
    comment?: string;
};

export type ServiceArea = {
    readonly uuid: string;
    name: string;
    zip_codes?: Array<string>;
    metro: Metro;
};

export type ServiceAreaRequest = {
    name: string;
    zip_codes?: Array<string>;
};

/**
 * * `residential` - Residential
 * * `commercial` - Commercial
 * * `buyers_agent` - Buyer's Agent
 * * `listing_agent` - Listing Agent
 */
export type SpecializationsEnum = 'residential' | 'commercial' | 'buyers_agent' | 'listing_agent';

/**
 * * `draft` - Draft
 * * `posted` - Posted
 * * `invited` - Invited
 * * `negotiating` - Negotiating
 * * `accepted` - Accepted
 * * `in_progress` - In Progress
 * * `completed` - Completed
 * * `cancelled` - Cancelled
 * * `disputed` - Disputed
 */
export type Status92cEnum = 'draft' | 'posted' | 'invited' | 'negotiating' | 'accepted' | 'in_progress' | 'completed' | 'cancelled' | 'disputed';

export type StripeConnectOnboardResponse = {
    url: string;
};

export type StripeWebhookRequestRequest = {
    payload: string;
};

export type StripeWebhookResponse = {
    status: string;
};

export type TokenObtainPair = {
    readonly access: string;
    readonly refresh: string;
};

export type TokenRefresh = {
    readonly access: string;
    refresh: string;
};

export type TokenRefreshRequest = {
    refresh: string;
};

/**
 * Serializer for user model.
 */
export type User = {
    first_name: string;
    last_name: string;
    /**
     * Email address
     */
    email: string;
    readonly url: string;
    avatar?: string | null;
};

/**
 * Serializer for user registration with password validation.
 */
export type UserRegistration = {
    /**
     * Email address
     */
    email: string;
    first_name: string;
    last_name: string;
};

/**
 * Serializer for user registration with password validation.
 */
export type UserRegistrationRequest = {
    /**
     * Email address
     */
    email: string;
    first_name: string;
    last_name: string;
};

/**
 * Serializer for user model.
 */
export type UserRequest = {
    first_name: string;
    last_name: string;
    /**
     * Email address
     */
    email: string;
    avatar?: Blob | File | null;
};

export type ConversationWritable = {
    [key: string]: unknown;
};

/**
 * Read serializer for gig list/detail.
 */
export type GigWritable = {
    title: string;
    description?: string;
    location_address: string;
    /**
     * Location latitude
     */
    location_lat?: string | null;
    /**
     * Location longitude
     */
    location_lng?: string | null;
    scheduled_date: string;
    scheduled_time: string;
    /**
     * Budget range minimum
     */
    budget_range_min?: string | null;
    /**
     * Budget range maximum
     */
    budget_range_max?: string | null;
    gig_type?: GigTypeEnum;
};

/**
 * Serializer for creating gigs.
 */
export type GigCreateRequestWritable = {
    title: string;
    description?: string;
    location_address: string;
    /**
     * Location latitude
     */
    location_lat?: string | null;
    /**
     * Location longitude
     */
    location_lng?: string | null;
    service_area_uuid?: string | null;
    scheduled_date: string;
    scheduled_time: string;
    /**
     * Budget range minimum
     */
    budget_range_min?: string | null;
    /**
     * Budget range maximum
     */
    budget_range_max?: string | null;
    gig_type?: GigTypeEnum;
};

/**
 * Read serializer for gig invitations.
 */
export type GigInvitationWritable = {
    proposed_rate?: string | null;
    message?: string;
    status?: GigInvitationStatusEnum;
};

export type MessageWritable = {
    body: string;
};

export type MetroWritable = {
    name: string;
    state: string;
};

/**
 * Extended serializer that includes private fields for the profile owner.
 */
export type MyProfessionalProfileWritable = {
    [key: string]: unknown;
};

/**
 * Serializer for password reset confirmation.
 */
export type PasswordResetConfirmRequestWritable = {
    token: string;
    password: string;
};

/**
 * Serializer for OTP-based password reset confirmation.
 */
export type PasswordResetOtpConfirmRequestWritable = {
    email: string;
    code: string;
    password: string;
};

/**
 * Serializer for creating/updating own professional profile.
 */
export type PatchedProfessionalProfileCreateRequestWritable = {
    license_number?: string;
    bio?: string;
    specializations?: Array<SpecializationsEnum>;
    is_available?: boolean;
    service_area_uuids?: Array<string>;
};

/**
 * Read-only serializer for viewing professional profiles (public).
 */
export type ProfessionalProfileWritable = {
    [key: string]: unknown;
};

/**
 * Serializer for creating/updating own professional profile.
 */
export type ProfessionalProfileCreateRequestWritable = {
    license_number: string;
    bio?: string;
    specializations?: Array<SpecializationsEnum>;
    is_available?: boolean;
    service_area_uuids?: Array<string>;
};

export type ReviewWritable = {
    [key: string]: unknown;
};

export type ServiceAreaWritable = {
    name: string;
    zip_codes?: Array<string>;
};

export type TokenRefreshWritable = {
    refresh: string;
};

/**
 * Serializer for user model.
 */
export type UserWritable = {
    first_name: string;
    last_name: string;
    /**
     * Email address
     */
    email: string;
    avatar?: string | null;
};

/**
 * Serializer for user registration with password validation.
 */
export type UserRegistrationRequestWritable = {
    /**
     * Email address
     */
    email: string;
    password: string;
    first_name: string;
    last_name: string;
};

export type ApiAuthPasswordResetOtpConfirmCreateData = {
    body: PasswordResetOtpConfirmRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset-otp/confirm/';
};

export type ApiAuthPasswordResetOtpConfirmCreateResponses = {
    200: PasswordResetOtpConfirm;
};

export type ApiAuthPasswordResetOtpConfirmCreateResponse = ApiAuthPasswordResetOtpConfirmCreateResponses[keyof ApiAuthPasswordResetOtpConfirmCreateResponses];

export type ApiAuthPasswordResetOtpRequestCreateData = {
    body: PasswordResetOtpRequestRequest;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset-otp/request/';
};

export type ApiAuthPasswordResetOtpRequestCreateResponses = {
    200: PasswordResetOtpRequest;
};

export type ApiAuthPasswordResetOtpRequestCreateResponse = ApiAuthPasswordResetOtpRequestCreateResponses[keyof ApiAuthPasswordResetOtpRequestCreateResponses];

export type ApiAuthPasswordResetConfirmCreateData = {
    body: PasswordResetConfirmRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset/confirm/';
};

export type ApiAuthPasswordResetConfirmCreateResponses = {
    200: PasswordResetConfirm;
};

export type ApiAuthPasswordResetConfirmCreateResponse = ApiAuthPasswordResetConfirmCreateResponses[keyof ApiAuthPasswordResetConfirmCreateResponses];

export type ApiAuthPasswordResetRequestCreateData = {
    body: PasswordResetRequestRequest;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset/request/';
};

export type ApiAuthPasswordResetRequestCreateResponses = {
    200: PasswordResetRequest;
};

export type ApiAuthPasswordResetRequestCreateResponse = ApiAuthPasswordResetRequestCreateResponses[keyof ApiAuthPasswordResetRequestCreateResponses];

export type ApiAuthRegisterCreateData = {
    body: UserRegistrationRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/register/';
};

export type ApiAuthRegisterCreateResponses = {
    201: UserRegistration;
};

export type ApiAuthRegisterCreateResponse = ApiAuthRegisterCreateResponses[keyof ApiAuthRegisterCreateResponses];

export type ApiAuthResendOtpCreateData = {
    body: ResendOtpRequest;
    path?: never;
    query?: never;
    url: '/api/auth/resend-otp/';
};

export type ApiAuthResendOtpCreateResponses = {
    200: ResendOtp;
};

export type ApiAuthResendOtpCreateResponse = ApiAuthResendOtpCreateResponses[keyof ApiAuthResendOtpCreateResponses];

export type ApiAuthTokenCreateData = {
    body: EmailTokenObtainPairRequest;
    path?: never;
    query?: never;
    url: '/api/auth/token/';
};

export type ApiAuthTokenCreateResponses = {
    200: TokenObtainPair;
};

export type ApiAuthTokenCreateResponse = ApiAuthTokenCreateResponses[keyof ApiAuthTokenCreateResponses];

export type ApiAuthTokenRefreshCreateData = {
    body: TokenRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/token/refresh/';
};

export type ApiAuthTokenRefreshCreateResponses = {
    200: TokenRefresh;
};

export type ApiAuthTokenRefreshCreateResponse = ApiAuthTokenRefreshCreateResponses[keyof ApiAuthTokenRefreshCreateResponses];

export type ApiAuthVerifyOtpCreateData = {
    body: OtpVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/auth/verify-otp/';
};

export type ApiAuthVerifyOtpCreateResponses = {
    200: OtpVerification;
};

export type ApiAuthVerifyOtpCreateResponse = ApiAuthVerifyOtpCreateResponses[keyof ApiAuthVerifyOtpCreateResponses];

export type ApiConversationsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/conversations/';
};

export type ApiConversationsListResponses = {
    200: PaginatedConversationList;
};

export type ApiConversationsListResponse = ApiConversationsListResponses[keyof ApiConversationsListResponses];

export type ApiConversationsCreateData = {
    body: ConversationCreateRequest;
    path?: never;
    query?: never;
    url: '/api/conversations/';
};

export type ApiConversationsCreateResponses = {
    201: ConversationCreate;
};

export type ApiConversationsCreateResponse = ApiConversationsCreateResponses[keyof ApiConversationsCreateResponses];

export type ApiConversationsMessagesListData = {
    body?: never;
    path: {
        conversation_uuid: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/conversations/{conversation_uuid}/messages/';
};

export type ApiConversationsMessagesListResponses = {
    200: PaginatedMessageList;
};

export type ApiConversationsMessagesListResponse = ApiConversationsMessagesListResponses[keyof ApiConversationsMessagesListResponses];

export type ApiConversationsMessagesCreateData = {
    body: MessageCreateRequest;
    path: {
        conversation_uuid: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_uuid}/messages/';
};

export type ApiConversationsMessagesCreateResponses = {
    201: MessageCreate;
};

export type ApiConversationsMessagesCreateResponse = ApiConversationsMessagesCreateResponses[keyof ApiConversationsMessagesCreateResponses];

export type ApiGigsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/gigs/';
};

export type ApiGigsListResponses = {
    200: PaginatedGigList;
};

export type ApiGigsListResponse = ApiGigsListResponses[keyof ApiGigsListResponses];

export type ApiGigsCreateData = {
    body: GigCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/gigs/';
};

export type ApiGigsCreateResponses = {
    201: GigCreate;
};

export type ApiGigsCreateResponse = ApiGigsCreateResponses[keyof ApiGigsCreateResponses];

export type ApiGigsInvitationsListData = {
    body?: never;
    path: {
        gig_uuid: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/gigs/{gig_uuid}/invitations/';
};

export type ApiGigsInvitationsListResponses = {
    200: PaginatedGigInvitationList;
};

export type ApiGigsInvitationsListResponse = ApiGigsInvitationsListResponses[keyof ApiGigsInvitationsListResponses];

export type ApiGigsInvitationsCreateData = {
    body: GigInvitationCreateRequest;
    path: {
        gig_uuid: string;
    };
    query?: never;
    url: '/api/gigs/{gig_uuid}/invitations/';
};

export type ApiGigsInvitationsCreateResponses = {
    201: GigInvitationCreate;
};

export type ApiGigsInvitationsCreateResponse = ApiGigsInvitationsCreateResponses[keyof ApiGigsInvitationsCreateResponses];

export type ApiGigsInvitationsRetrieveData = {
    body?: never;
    path: {
        gig_uuid: string;
        uuid: string;
    };
    query?: never;
    url: '/api/gigs/{gig_uuid}/invitations/{uuid}/';
};

export type ApiGigsInvitationsRetrieveResponses = {
    200: GigInvitation;
};

export type ApiGigsInvitationsRetrieveResponse = ApiGigsInvitationsRetrieveResponses[keyof ApiGigsInvitationsRetrieveResponses];

export type ApiGigsInvitationsPartialUpdateData = {
    body?: PatchedGigInvitationRequest;
    path: {
        gig_uuid: string;
        uuid: string;
    };
    query?: never;
    url: '/api/gigs/{gig_uuid}/invitations/{uuid}/';
};

export type ApiGigsInvitationsPartialUpdateResponses = {
    200: GigInvitation;
};

export type ApiGigsInvitationsPartialUpdateResponse = ApiGigsInvitationsPartialUpdateResponses[keyof ApiGigsInvitationsPartialUpdateResponses];

export type ApiGigsInvitationsUpdateData = {
    body?: GigInvitationRequest;
    path: {
        gig_uuid: string;
        uuid: string;
    };
    query?: never;
    url: '/api/gigs/{gig_uuid}/invitations/{uuid}/';
};

export type ApiGigsInvitationsUpdateResponses = {
    200: GigInvitation;
};

export type ApiGigsInvitationsUpdateResponse = ApiGigsInvitationsUpdateResponses[keyof ApiGigsInvitationsUpdateResponses];

export type ApiGigsRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/gigs/{uuid}/';
};

export type ApiGigsRetrieveResponses = {
    200: Gig;
};

export type ApiGigsRetrieveResponse = ApiGigsRetrieveResponses[keyof ApiGigsRetrieveResponses];

export type ApiGigsPartialUpdateData = {
    body?: PatchedGigRequest;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/gigs/{uuid}/';
};

export type ApiGigsPartialUpdateResponses = {
    200: Gig;
};

export type ApiGigsPartialUpdateResponse = ApiGigsPartialUpdateResponses[keyof ApiGigsPartialUpdateResponses];

export type ApiGigsUpdateData = {
    body: GigRequest;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/gigs/{uuid}/';
};

export type ApiGigsUpdateResponses = {
    200: Gig;
};

export type ApiGigsUpdateResponse = ApiGigsUpdateResponses[keyof ApiGigsUpdateResponses];

export type ApiGigsTransitionCreateData = {
    body: GigStatusTransitionRequest;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/gigs/{uuid}/transition/';
};

export type ApiGigsTransitionCreateResponses = {
    200: Gig;
};

export type ApiGigsTransitionCreateResponse = ApiGigsTransitionCreateResponses[keyof ApiGigsTransitionCreateResponses];

export type ApiMetrosListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/metros/';
};

export type ApiMetrosListResponses = {
    200: PaginatedMetroList;
};

export type ApiMetrosListResponse = ApiMetrosListResponses[keyof ApiMetrosListResponses];

export type ApiPaymentsRetrieveData = {
    body?: never;
    path: {
        gig_uuid: string;
    };
    query?: never;
    url: '/api/payments/{gig_uuid}/';
};

export type ApiPaymentsRetrieveResponses = {
    200: PaymentDetailResponse;
};

export type ApiPaymentsRetrieveResponse = ApiPaymentsRetrieveResponses[keyof ApiPaymentsRetrieveResponses];

export type ApiPaymentsStripeConnectCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/stripe-connect/';
};

export type ApiPaymentsStripeConnectCreateResponses = {
    200: StripeConnectOnboardResponse;
};

export type ApiPaymentsStripeConnectCreateResponse = ApiPaymentsStripeConnectCreateResponses[keyof ApiPaymentsStripeConnectCreateResponses];

export type ApiPaymentsWebhookCreateData = {
    body: StripeWebhookRequestRequest;
    path?: never;
    query?: never;
    url: '/api/payments/webhook/';
};

export type ApiPaymentsWebhookCreateResponses = {
    200: StripeWebhookResponse;
};

export type ApiPaymentsWebhookCreateResponse = ApiPaymentsWebhookCreateResponses[keyof ApiPaymentsWebhookCreateResponses];

export type ApiProfessionalsListData = {
    body?: never;
    path?: never;
    query?: {
        is_available?: boolean;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/professionals/';
};

export type ApiProfessionalsListResponses = {
    200: PaginatedProfessionalProfileList;
};

export type ApiProfessionalsListResponse = ApiProfessionalsListResponses[keyof ApiProfessionalsListResponses];

export type ApiProfessionalsRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/professionals/{uuid}/';
};

export type ApiProfessionalsRetrieveResponses = {
    200: ProfessionalProfile;
};

export type ApiProfessionalsRetrieveResponse = ApiProfessionalsRetrieveResponses[keyof ApiProfessionalsRetrieveResponses];

export type ApiProfessionalsReviewsListData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/professionals/{uuid}/reviews/';
};

export type ApiProfessionalsReviewsListResponses = {
    200: PaginatedReviewList;
};

export type ApiProfessionalsReviewsListResponse = ApiProfessionalsReviewsListResponses[keyof ApiProfessionalsReviewsListResponses];

export type ApiProfessionalsMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/professionals/me/';
};

export type ApiProfessionalsMeRetrieveResponses = {
    200: MyProfessionalProfile;
};

export type ApiProfessionalsMeRetrieveResponse = ApiProfessionalsMeRetrieveResponses[keyof ApiProfessionalsMeRetrieveResponses];

export type ApiProfessionalsMePartialUpdateData = {
    body?: PatchedProfessionalProfileCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/professionals/me/';
};

export type ApiProfessionalsMePartialUpdateResponses = {
    200: MyProfessionalProfile;
};

export type ApiProfessionalsMePartialUpdateResponse = ApiProfessionalsMePartialUpdateResponses[keyof ApiProfessionalsMePartialUpdateResponses];

export type ApiProfessionalsMeCreateData = {
    body: ProfessionalProfileCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/professionals/me/';
};

export type ApiProfessionalsMeCreateResponses = {
    201: MyProfessionalProfile;
};

export type ApiProfessionalsMeCreateResponse = ApiProfessionalsMeCreateResponses[keyof ApiProfessionalsMeCreateResponses];

export type ApiReviewsCreateData = {
    body: ReviewCreateRequest;
    path?: never;
    query?: never;
    url: '/api/reviews/';
};

export type ApiReviewsCreateResponses = {
    201: ReviewCreate;
};

export type ApiReviewsCreateResponse = ApiReviewsCreateResponses[keyof ApiReviewsCreateResponses];

export type ApiServiceAreasListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/service-areas/';
};

export type ApiServiceAreasListResponses = {
    200: PaginatedServiceAreaList;
};

export type ApiServiceAreasListResponse = ApiServiceAreasListResponses[keyof ApiServiceAreasListResponses];

export type ApiUsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/users/';
};

export type ApiUsersListResponses = {
    200: PaginatedUserList;
};

export type ApiUsersListResponse = ApiUsersListResponses[keyof ApiUsersListResponses];

export type ApiUsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersRetrieveResponses = {
    200: User;
};

export type ApiUsersRetrieveResponse = ApiUsersRetrieveResponses[keyof ApiUsersRetrieveResponses];

export type ApiUsersPartialUpdateData = {
    body?: PatchedUserRequest;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersPartialUpdateResponses = {
    200: User;
};

export type ApiUsersPartialUpdateResponse = ApiUsersPartialUpdateResponses[keyof ApiUsersPartialUpdateResponses];

export type ApiUsersUpdateData = {
    body: UserRequest;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersUpdateResponses = {
    200: User;
};

export type ApiUsersUpdateResponse = ApiUsersUpdateResponses[keyof ApiUsersUpdateResponses];

export type ApiUsersChangePasswordCreateData = {
    body: PasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/api/users/change-password/';
};

export type ApiUsersChangePasswordCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ApiUsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type ApiUsersMeRetrieveResponses = {
    200: User;
};

export type ApiUsersMeRetrieveResponse = ApiUsersMeRetrieveResponses[keyof ApiUsersMeRetrieveResponses];

export type ApiUsersMePartialUpdateData = {
    body?: PatchedUserRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type ApiUsersMePartialUpdateResponses = {
    200: User;
};

export type ApiUsersMePartialUpdateResponse = ApiUsersMePartialUpdateResponses[keyof ApiUsersMePartialUpdateResponses];
