# Generated by Django 5.2.7 on 2026-03-16 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location_address', models.CharField(max_length=500, verbose_name='location address')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='location latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='location longitude')),
                ('scheduled_date', models.DateField(verbose_name='scheduled date')),
                ('scheduled_time', models.TimeField(verbose_name='scheduled time')),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='budget range minimum')),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='budget range maximum')),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='agreed price')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('invited', 'Invited'), ('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='draft', max_length=20, verbose_name='status')),
                ('gig_type', models.CharField(choices=[('showing', 'Showing'), ('open_house', 'Open House'), ('inspection_accompaniment', 'Inspection Accompaniment'), ('other', 'Other')], default='showing', max_length=30, verbose_name='gig type')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gigs', to='professionals.professionalprofile', verbose_name='assigned to')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_gigs', to='professionals.professionalprofile', verbose_name='posted by')),
                ('service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs', to='professionals.servicearea', verbose_name='service area')),
            ],
            options={
                'verbose_name': 'gig',
                'verbose_name_plural': 'gigs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GigInvitation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='proposed rate')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20, verbose_name='status')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='gigs.gig', verbose_name='gig')),
                ('invited_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_invitations', to='professionals.professionalprofile', verbose_name='invited agent')),
            ],
            options={
                'verbose_name': 'gig invitation',
                'verbose_name_plural': 'gig invitations',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['status'], name='gigs_gig_status_0057ec_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['posted_by', 'status'], name='gigs_gig_posted__23af57_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['assigned_to', 'status'], name='gigs_gig_assigne_49cd17_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['scheduled_date'], name='gigs_gig_schedul_399976_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['service_area'], name='gigs_gig_service_4a3304_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='giginvitation',
            unique_together={('gig', 'invited_agent')},
        ),
    ]
