# Generated by Django 5.2.7 on 2026-03-16 21:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gigs', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('is_from_poster', models.BooleanField(verbose_name='is from poster')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gigs.gig', verbose_name='gig')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='professionals.professionalprofile', verbose_name='reviewee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='professionals.professionalprofile', verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created'],
                'unique_together': {('gig', 'reviewer', 'reviewee')},
            },
        ),
    ]
