# Generated by Django 5.2.7 on 2026-03-16 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe PaymentIntent ID')),
                ('stripe_transfer_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Transfer ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='platform fee')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('released', 'Released'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('gig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='gigs.gig', verbose_name='gig')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created'],
            },
        ),
    ]
