# Generated by Django 5.2.7 on 2026-03-16 21:13

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('state', models.CharField(max_length=2, verbose_name='state')),
            ],
            options={
                'verbose_name': 'metro',
                'verbose_name_plural': 'metros',
                'ordering': ['state', 'name'],
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('zip_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None, verbose_name='zip codes')),
                ('metro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='professionals.metro', verbose_name='metro')),
            ],
            options={
                'verbose_name': 'service area',
                'verbose_name_plural': 'service areas',
                'ordering': ['name'],
                'unique_together': {('name', 'metro')},
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='license number')),
                ('license_status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending_verification', max_length=25, verbose_name='license status')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='license expiry')),
                ('specializations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('buyers_agent', "Buyer's Agent"), ('listing_agent', 'Listing Agent')], max_length=25), blank=True, default=list, size=None, verbose_name='specializations')),
                ('bio', models.TextField(blank=True, default='', verbose_name='bio')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='average rating')),
                ('average_response_time', models.DurationField(blank=True, null=True, verbose_name='average response time')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('stripe_connect_account_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Connect account ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('last_reverification_check', models.DateTimeField(blank=True, null=True, verbose_name='last reverification check')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='rejection reason')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
                ('service_areas', models.ManyToManyField(blank=True, related_name='professionals', to='professionals.servicearea', verbose_name='service areas')),
            ],
            options={
                'verbose_name': 'professional profile',
                'verbose_name_plural': 'professional profiles',
                'indexes': [models.Index(fields=['license_status'], name='professiona_license_03168e_idx'), models.Index(fields=['is_available'], name='professiona_is_avai_8468fc_idx'), models.Index(fields=['license_number'], name='professiona_license_716c64_idx')],
            },
        ),
    ]
